services:
  web:
    build: .
    ports:
      - 8000:80
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fastapi
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin

